export const USER_LOGIIN_REQUEST = 'USER_LOGIIN_REQUEST';
export const USER_LOGIIN_SUCCESS = 'USER_LOGIIN_SUCCESS';
export const USER_LOGIIN_FAIL = 'USER_LOGIIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';
